CREATE TABLE `user` (
    `uid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `nickname` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '用户名',
    `mobile` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '手机号码',
    `email` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '邮箱地址',
    `sex` INT NOT NULL DEFAULT 0 COMMENT '1：男 2：女 0：没填写',
    `avatar` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '头像',
    `login_name` VARCHAR(20) NOT NULL UNIQUE DEFAULT '' COMMENT '登录用户名',
    `login_pwd` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '登录密码',
    `login_salt` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '登录密码的随机加密秘钥',
    `status` INT NOT NULL DEFAULT 1 COMMENT '1：有效 0：无效',
    `updated_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后一次更新时间',
    `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
    PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';
